<?php
include 'php/site-config.php';
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Airportzo | Terms and Conditions</title>
    <link rel="shortcut icon" id="favicon-logo">
    <link rel="stylesheet" href="css/bootstrap.min.3.3.5.css">
    <link rel="stylesheet" href="css/bootstrap-icons.css">
    <link rel="stylesheet" href='css/bootstrap-datetimepicker.css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/intlTelInput.css"/>
    <link rel="stylesheet" href="css/fonts.css">

    <link rel="stylesheet" href="css/main.css<?php echo $cache_str; ?>">
    <link rel="stylesheet" href="css/custom.css<?php echo $cache_str; ?>">
    <link rel="stylesheet" href="css/home.css<?php echo $cache_str; ?>">
    <link rel="stylesheet" href="css/terms.css<?php echo $cache_str; ?>">

    <script src="js/onloads.js<?php echo $cache_str; ?>"></script>
</head>

<body onload="loadDistributorDetail();">
    <div id="loading"></div>

    <!-- NAV MENU -->
    <nav></nav>
    <section class="terms-sec">
        <input type="hidden" id="gtag_id">
        <div class="container">
            <div class="heading-set">
                <h2>Terms And Conditions</h2>
            </div>
            <div class="terms__container">
                <div class="sub__terms-container">
                    <h4>TERMS AND CONDITIONS OF USE OF MEET AND GREET SERVICE</h4>
                    <p>This is an electronic contract in terms of Information Technology Act, 2000 and rules there under, as applicable. This electronic contract is generated by a computer system and does not require any physical or digital signatures.</p>
                    <p>The Terms and Conditions for Acceptable Use of Website and Services (Terms and Conditions) sets out, inter alia, a list of acceptable and unacceptable conduct for use of the Services sold on www.AirportZo.com (Service). These Terms and Conditions create a binding legal agreement between a person using or accessing this Website or availing the Service through the Website (you or Passenger) and AirportZo Private Limited (AirportZo, we, our or us) Authorized Licensee of the online marketplace and consolidator portal www.AirportZo.com for Meet and Assist service providers, airport lounge, baggage porters and other similar ancillary service providers at Airports in India and abroad.</p>
                    <p>If we believe a violation of these Terms and Conditions is deliberate, repeated or presents a credible risk of harm to other users, or the Services or any third parties, we may suspend or terminate your access.</p>
                    <p>The Service shall be provided by various third-party operators at various airports (Service Providers). This website (www.AirportZo.com/) is solely, developed, operated and maintained by AirportZo.</p>
                    <p>It is explicitly clarified to you that AirportZo Private Limited. (owner of the brand name “AirportZo”
                        under which it operates this portal) is not in any way involved in providing the Service and shall not be
                        liable in case of any complaints or grievances of the Passengers or losses incurred or injury suffered by
                        Passengers in reference to the Service purchased by the Passengers through the Website or otherwise.
                        AirportZo Private Limited. does not provide any representation, warranty, or guarantee regarding the
                        Service being purchased through the Website.</p>
                    <p>By accessing this Website through any computing or mobile platform, you acknowledge that you have
                        carefully read and understood the Terms and Conditions and agree to be bound by them for as long as
                        you are accessing the Website or requesting Services from AirportZo. Please note that these Terms and
                        Conditions read together with the Privacy Policy (www.AirportZo.com/privacy-policy) constitute a legal
                        and binding agreement between you and AirportZo (Agreement) and is enforceable under the laws of
                        India. There may be certain Service Provider terms and privacy policies which may be applicable to the
                        Services, which may be appended to these Terms and Conditions, set out at the point of access to the
                        relevant Service Provider portals or referred at such other appropriate place. You are also responsible
                        for reading them and complying with them. Any data that you submit to such Service Providers shall be
                        governed by the Service Provider privacy policies. We have no control over the conduct of any Service
                        Providers and their use of data and disclaim any and all liability in this regard to the maximum extent
                        permitted by applicable law.</p>
                    <p>By accepting the Terms and Conditions, you represent and warrant that you are at least 18 years of age
                        and have the right, authority, and legal capacity to enter into this Agreement. If, at any time, we are of
                        the opinion that you do not satisfy the eligibility criteria, or that you have made any misrepresentation
                        about your eligibility, we retain the right to disable your access to the Website and/or suspend the
                        Services immediately.</p>
                    <p>AirportZo reserves the right to amend, add to, change or remove any part of these Terms and
                        Conditions at any time, without notice. Any changes to these Terms and Conditions or any terms posted
                        on the Website apply as soon as they are posted. By continuing to use the Website after any changes
                        are posted, you are indicating your acceptance of those changes.</p>
                    <p>IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS, PLEASE DISCONTINUE USING THE WEBSITE
                        AND SERVICES IMMEDIATELY AND REFRAIN FROM ACCESSING ANY CONTENT ON THE WEBSITE
                        HENCEFORTH.</p>
                </div>
                <div class="sub__terms-container">
                    <h4>TERMS AND CONDITIONS OF USE OF WEBSITE</h4>
                    <p><span class="sub__head">1. Ownership of Materials & Appropriate Use</span>
                        This Website and the materials on it, including the content, data, design, information or other materials
                        available on and underlying the Website, are protected by copyright, trademark and other intellectual
                        property rights and laws throughout the world. The materials on the Website are owned by or licensed
                        to us. You may not alter, broadcast, copy, distribute, modify, publish, sell, license, communicate to the
                        public, adapt, modify, translate, disassemble, decompile or reverse engineer, create derivative works
                        from, or in any way use or exploit or transfer any materials on this Website although you are permitted
                        to display the materials on the Website on a computer screen and to download and print a hard copy for
                        your personal use in connection with the Services availed by you provided you do not alter or remove
                        any copyright, trademark or other proprietary notices. We grant you a non-sub-licensable, revocable,
                        non-transferable, non-exclusive, limited period license to use this Website, but solely as necessary to
                        use our Services and in accordance with the Terms and Conditions. All of our rights not expressly
                        granted by this license are hereby retained.</p>
                    <p>Copying of part or all the contents of this Website without permission of AirportZo is prohibited except
                        to the extent that such copying/printing is necessary for the purposes of availing of the Services.</p>
                    <p>You agree to use the Website in accordance with these Terms and Conditions of Use for lawful and
                        proper purposes and in compliance with the laws of the country from which you are accessing the
                        Website. Further, you agree to:</p>
                    <ul>
                        <li>Comply with all applicable laws and governmental regulations, including, but not limited to, all
                            intellectual property, data, privacy, and export control laws, and regulations of any government
                            agencies.</li>
                        <li>Hold only one account per person and be solely responsible for the use and management of
                            your account and password.</li>
                        <li>Keep passwords and all other login information confidential.</li>
                        <li>Monitor and control all activity conducted through your account in connection with the access
                            to the Website and Services.</li>
                        <li>Promptly notify us if you become aware of or reasonably suspect any illegal or unauthorized
                            activity or a security breach involving your accounts or teams, including any loss, theft, or
                            unauthorized disclosure or use of a username, password, or account.</li>
                        <li>Provide us with reasonable assistance, as requested, to stop or remedy any illegal or
                            unauthorized activity or a security breach.</li>
                        <li>Comply in all respects with all applicable terms of the third-party applications, integrated with
                            the Services that you access or subscribe to in connection with the Services.</li>
                    </ul>
                    <p>You may be held liable for losses incurred by us or any other user of the Website or Services due to
                        authorized or unauthorized use of your account as a result of your failure in keeping your account
                        information secure and confidential and/or not promptly notifying us in the event of any breach of
                        security.</p>
                    <p>Furthermore, you agree not to:</p>
                    <ul>
                        <li>Use any of the materials on this Website for commercial exploitation without our prior written
                            consent.</li>
                        <li>Any other website, intranet or extranet site
                            without our prior written consent; obtain or attempt to obtain or permit any un-authorized
                            access to our intranet or any other restricted access networks or any account on the Website.</li>
                        <li>Upload to, or transmit from, the Website any data, file, software, or link that contains or
                            redirects to a virus, trojan horse, worm, or other harmful component or a technology that
                            unlawfully accesses or downloads content or information stored on the Website or on the
                            hardware of AirportZo or any third party.</li>
                        <li>
                            Post, upload, publish, transmit or share any information that.
                            <p class="sub__list">1. belongs to another person and to which you do not have any right.</p>
                            <p class="sub__list">2. is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic,
                                pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically
                                objectionable, disparaging, relating or encouraging money laundering or gambling, or
                                otherwise unlawful in any manner whatsoever.</p>
                            <p class="sub__list">3. harm minors in any way.</p>
                            <p class="sub__list">4. infringes any patent, trademark, copyright or other proprietary rights.</p>
                            <p class="sub__list">5. violates any law for the time being in force.</p>
                            <p class="sub__list">6. deceives or misleads the addressee about the origin of such messages or communicates
                                any information which is grossly offensive or menacing in nature.</p>
                            <p class="sub__list">7. impersonates another person.</p>
                            <p class="sub__list">8. contains software viruses or any other computer code, files or programs designed to
                                interrupt, destroy or limit the functionality of any computer resource; or</p>
                            <p class="sub__list">9. threatens the unity, integrity, defense, security or sovereignty of India, friendly relations
                                with foreign states, or public order or causes incitement to the commission of any
                                cognizable offence or prevents investigation of any offence or is insulting any other
                                nation.</p>
                        </li>
                    </ul>
                    <p>Posting, uploading, publishing, transmitting or sharing any information that has been listed in clause (i)
                        to clause (ix) above may lead to suspension of your account. In the event we receive any complaint that
                        any information posted by you amounts to a breach of this clause, we will take such steps necessary as
                        required under law to remove or disable access to such information and may suspend or terminate your
                        account at its sole discretion.</p>
                    <ul>
                        <li>Attempt to reverse engineer, decompile, hack, disable, interfere with, disassemble, modify, copy,
                            translate, or disrupt the features, functionality, integrity, or performance of the Website
                            (including any mechanism used to restrict or control the functionality of the Website), any third
                            party use of the Website, or any third-party data contained therein (except to the extent such
                            restrictions are prohibited by applicable law).</li>
                        <li>Interfere with the proper functioning of the Website.</li>
                        <li>Access the Website or Services in order to build a similar or competitive product or service or
                            copy any ideas, features, functions, or graphics of the Website or Service.</li>
                        <li>Access, search, or create accounts for the Website/Services by any means other than our publicly
                            supported interfaces (for example, "scraping" or creating accounts in bulk). •Distribute, publish,
                            send, or facilitate the sending of unsolicited mass e-mail or other messages, promotions,
                            advertising, or solicitations (like “spam”), including commercial advertising and informational
                            announcements.</li>
                        <li>Abuse referrals or promotions (if any) to get more credits than deserved.</li>
                        <li>Resell, time share or similarly exploit the Services.</li>
                        <li>Use contact or other user information obtained from the Website (including email addresses) to
                            contact users outside of the Services without their express permission or authority or to create
                            or distribute mailing lists or other collections of contact or user profile information for use for
                            use outside of the Service; or</li>
                        <li>Authorize, permit, enable, induce or encourage any third party to do any of the above.</li>
                    </ul>
                    <p><span class="sub__head">2. Website Availability and Content</span>This Website is provided free of charge and we make no guarantee that it will be uninterrupted or error
                        free. We make no guarantee as to availability, quality or service levels of the Website or Services on a
                        24x7 basis or promise uninterrupted access to the Website or Services. Disruption of Website or Services
                        may arise due to technical or operational difficulties, and no prior notice of downtime will be given to
                        you in such circumstances. We reserve the right to suspend or withdraw the whole or materials or
                        information on the Website at any time without notice. We may also suspend the Services for specific
                        users permanently or temporarily for any reason whatsoever, including while investigating complaints or
                        alleged violations of these Terms and Conditions.</p>
                    <p>AirportZo may add, change, discontinue, remove or suspend any other content posted on the Website,
                        including features and specifications of products described or depicted on the Website, temporarily or
                        permanently, at any time, without notice and without liability.</p>
                    <p><span class="sub__head">3. Links from this Site</span>
                        We may from time to time provide links from this Website to websites that are owned and controlled by
                        third parties. These links are provided for your convenience only and do not imply any affiliation or
                        endorsement by AirportZo. We have no control over and shall have no liability whatsoever in respect of
                        those websites.</p>
                    <p><span class="sub__head">4. Accuracy of Information</span>We take reasonable care to ensure that all products and services information and pricing featured on
                        this website is accurate and up-to-date. However, our products and services are continually updated and
                        the images, specifications [and any prices] on the Website are for general illustrative guidance only.</p>
                    <p><span class="sub__head">5. Disclaimer</span>We provide the Services and the content on the Website on an "as is" basis and grant no warranties of
                        any kind, whether express, implied, statutory or otherwise with respect to the Services and content on
                        the Website. We specifically disclaim any implied warranties of fitness for a particular purpose or non
                        infringement. You expressly agree that the use of the Website and Services is at your own risk. We do
                        not warrant, represent or undertake that the material on the Website is accurate, complete or current
                        or that the Website will be free or defects or viruses and all conditions and warranties that might
                        otherwise be implied by statute or at common law are excluded to the fullest extent permitted by law.
                        We do not accept any liability for any losses or claims arising from any liability to access the Website,
                        use of the Website, downloading of viruses, the loss or corruption to material that is downloaded and
                        any website browser incompatibility problems. All software products downloaded from this website are
                        downloaded, installed and used at the user's own risk.</p>
                    <p><span class="sub__head">5. Disclaimer</span>We provide the Services and the content on the Website on an "as is" basis and grant no warranties of
                        any kind, whether express, implied, statutory or otherwise with respect to the Services and content on
                        the Website. We specifically disclaim any implied warranties of fitness for a particular purpose or non
                        infringement. You expressly agree that the use of the Website and Services is at your own risk. We do
                        not warrant, represent or undertake that the material on the Website is accurate, complete or current
                        or that the Website will be free or defects or viruses and all conditions and warranties that might
                        otherwise be implied by statute or at common law are excluded to the fullest extent permitted by law.
                        We do not accept any liability for any losses or claims arising from any liability to access the Website,
                        use of the Website, downloading of viruses, the loss or corruption to material that is downloaded and
                        any website browser incompatibility problems. All software products downloaded from this website are
                        downloaded, installed and used at the user's own risk.</p>
                    <p><span class="sub__head">6. Privacy Policy</span>Use of the Website and Services is also governed by the Privacy Policy. You acknowledge that you have
                        carefully read the Privacy Policy and understood the practices and policies that govern the use of the
                        Website and Services, and hereby consent to the collection, storage, processing, disclosure and transfer
                        of any personal or sensitive personal information provided by you to us, as set out in the Privacy Policy.
                        You have the option to not provide your consent for the collection or processing of sensitive personal
                        information, and to withdraw your consent at any point of time, provided that in such cases we will not
                        be able to provide a full range of Services to you.</p>
                    <p><span class="sub__head">7. Law and Jurisdiction</span>Your use of the Website and any downloaded material from it and the interpretation of these Terms and
                        Conditions shall be governed by the laws of India and all matters related to these Terms and Conditions
                        are submitted to the exclusive jurisdiction of the courts at New Delhi.</p>
                    <p>You represent and warrant that you shall:</p>
                    <p class="sub__list">1. not use the Website in a manner that results in AirportZo breaching any laws or regulations; and</p>
                    <p class="sub__list">2. not violate or infringe any third-party rights, including without limitation, intellectual property
                        rights and publicity/privacy rights.</p>
                    <p class="sub__list">3. Limitation of Liability</p>
                    <p>WE WILL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY SPECIAL, INDIRECT, INCIDENTAL,
                        CONSEQUENTIAL OR PUNITIVE DAMAGES (SUCH AS LOSS OF PROFITS, LOSS OF GOODWILL, LOSS OF
                        USE, LOSS OF DATA, BUSINESS INTERRUPTION, OR OTHER INTANGIBLE LOSSES) ARISING OUT OF OR
                        RELATING IN ANY WAY TO THE SERVICES, OUR CONTENT, OR USE OF THE WEBSITE.
                        IN NO EVENT WILL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE
                        USE OF, OR ANY INABILITY TO USE ANY PORTION OF SERVICES, OR OTHERWISE ARISING OUT OF OR
                        RELATING TO THE TERMS AND CONDITIONS /AGREEMENT, WHETHER IN CONTRACT, TORT, OR
                        OTHERWISE, EXCEED IN THE AGGREGATE AMOUNT RECEIVED FROM YOU FOR THE SERVICE AVAILED BY
                        YOU.</p>
                    <p><span class="sub__head">8. Indemnity</span>You agree to indemnify and hold harmless AirportZo and its subsidiaries, affiliates, officers, directors,
                        agents, and third parties, for any losses, liabilities and expenses (including reasonable attorney's fees)
                        relating to or arising out of your use of the Website and Services and/or arising from a breach of these
                        Terms and Conditions, any violation of third party data protection rights, and/or any breach of your
                        representations and warranties set forth above and/or any fraudulent act on your part.</p>
                    <p><span class="sub__head">9. Termination</span>Any violation or breach of the Terms and Conditions may lead to automatic suspension or termination of
                        your account and access to the Website and Services, and we shall not be responsible or liable for any
                        damages in this regard. The termination of your account will not affect any liability that may have arisen
                        prior to the date of termination.</p>
                </div>
                <div class="sub__terms-container">
                    <h4>TERMS AND CONDITIONS OF USE OF MEET & ASSIST SERVICE</h4>
                    <p>1.1. The Service shall also be governed by the terms and conditions of the respective Service Providers.</p>
                    <p>1.2. It is explicitly clarified to Passengers that AirportZo Private Limited. Limited (owner of the brand
                        name “AirportZo” under which it operates its air transport services) is not in any way involved in
                        providing the Service to the Passenger(s) and shall not be liable in case of any complaints or grievances
                        of the Passengers or losses incurred or injury suffered by Passenger in reference to the Service
                        purchased by the Passengers through the Website. AirportZo Private Limited. does not provide any
                        representation, warranty, or guarantee regarding the Service being purchaser through the Website.</p>
                    <p>1.3. Neither AirportZo nor shall be liable for any loss or damage that may be suffered by a Passenger,
                        directly or indirectly, as a result of purchasing the Service through the Website. All complaints, claims,
                        disputes, concerns and issues, regarding the Service at a particular airport, will need to be taken up
                        directly with the respective Service Provider. AirportZo shall in no manner be responsible for the same.
                        However, AirportZo will assist Passengers in communicating with the respective Service Providers
                        through email.</p>
                    <p>1.4. By purchasing the Service through the Website, each Passenger: (i) unconditionally and irrevocably
                        agrees to these terms and conditions; and (ii) acknowledges that its personal data including name and
                        geographic location, may be shared by AirportZo with the Service Providers in accordance with
                        AirportZo’s privacy policy.</p>
                    <p>1.5. AirportZo and the respective Service Providers shall at their sole discretion, be entitled to cancel,
                        alter or omit any part of the Service with or without notification to Passenger(s) at its sole discretion. In
                        such cases, the AirportZo’s/respective Service Provider’s liability shall be limited to re-performance of
                        the cancelled Service. In cases where AirportZo is unable to ensure that the Service is re-performed
                        and/or their respective Service Provider is unable to re-perform the Service, a partial/full refund may be
                        provided by AirportZo to Passengers at its sole discretion.</p>
                    <p>1.6. Delays and cancellations of the Service by AirportZo and/or their respective Service Providers may
                        result from factors beyond their control such as the accidents, government restrictions, acts of God, war
                        and other force majeure events. In such cases, AirportZo’s and the Service Providers’ liability shall be
                        limited to re-performance of the cancelled Service.</p>
                    <p>1.7. In case a Passenger/Passengers is/are in breach of any Terms and Conditions and/or terms and
                        conditions of the Service Providers, AirportZo and its respective Service Providers shall at all times
                        reserve the right to withdraw the Service by informing the Passenger of such withdrawal without
                        assigning any reason and without further reference. In such cases, Neither the AirportZo nor the Service
                        Provider will be liable to re-perform the Service or to provide the Passenger(s) with a refund.</p>
                    <p>1.8. Passengers shall not use the Service or its reference for any unlawful or prohibited purposes.</p>
                    <p>1.9. In case of any misconduct or any unlawful or prohibited activity being conducted by the Passenger,
                        AirportZo and their respective Service Providers may, at their sole discretion, decline to provide the
                        Service to any Passenger. In such cases, neither the AirportZo nor the Service Provider will be liable to
                        re-perform the Service or to provide the Passenger(s) with a refund.</p>
                    <p>1.10. AirportZo and their respective Service Providers’ liability towards a Passenger, if any, shall in no
                        event exceed the total charges paid by the Passenger for the Service through the Website. Under no
                        circumstances shall AirportZo and their respective Service Providers be liable for any consequential,
                        exemplary, special, indirect, incidental or punitive damages. It is clarified that AirportZo Private Limited.
                        will not be liable towards a Passenger for any damages, refunds, or any other payments.</p>
                    <p>1.11. Passengers agree to indemnify AirportZo in respect to all claims, damages, losses, costs, and
                        expenses (including legal expenses) which are awarded against or incurred by AirportZo and/or their
                        respective Service Providers as a direct result of acts or omissions by Passenger(s) either during the
                        course of booking and/or using the Service.</p>
                    <p>1.12. AirportZo and its respective Service Providers shall not be liable for the consequences of any delay
                        or for any loss, cost or expense incurred by Passenger as a result of the actions of any other party
                        including without limitation any airline, customs and immigration authorities etc.</p>
                    <p>1.13. In relation to the Service, AirportZo and its respective Service Providers accept no liability for any
                        items left or disclaimed by the Passenger(s).</p>
                    <p>1.14. By offering Services, AirportZo and their respective Service Providers do not accept any liability for
                        damages, losses, or delays that may result on account of improper documents including without
                        limitation possession of invalid ticket, invalid visa, invalid passport or due to any other requirement in
                        relation to entry, exist, length of stay, special permissions etc. as may be required for traveling through respective airports.</p>
                    <p>1.15. AirportZo reserves the right to undertake all necessary steps to ensure that the security, safety and
                        integrity of AirportZo’s systems and Passenger interests are and remain, well-protected.</p>
                    <p>1.16. AirportZo may take various steps to verify and confirm the authenticity and validity of air travel
                        reservations made by Passengers.</p>
                    <p>1.17. If AirportZo.com , at its sole and exclusive discretion, concludes that any air travel reservation
                        of a Passenger is not or does not reasonably appear to be authentic, enforceable or valid, then
                        AirportZo may cancel the corresponding reservation for the Service any time before or during the
                        Service.</p>
                    <p>1.18. Any communications or materials sent to support@AirportZo.com by electronic mail or sent to
                        AirportZo otherwise, including any comments, data, questions, suggestions or the like, all such
                        communications are, as may be received by AirportZo will be treated by AirportZo as non-confidential
                        and may be used for training, quality monitoring, legal and compliance purposes. You are therefore
                        advised not to present any personal data or information in such communications.</p>
                    <p>1.19. Passengers hereby give up any and all claims that any use of such[ material violates any of
                        Passengers rights including moral rights, privacy rights, proprietary or other property rights, publicity
                        rights, rights to credit for material or ideas, or any other right, including the right to approve the way
                        AirportZo uses such material.</p>
                    <p>1.20. Any material submitted to the Website may be adapted, broadcast, changed, copied, disclosed,
                        licensed, performed, posted, published, transmitted or used by AirportZo anywhere in the world, in any
                        medium, forever. Passenger(s) agrees that it has read the Privacy Policy as provided on the Website.</p>
                    <p>1.21. Passengers acknowledge that Internet transmissions are never completely private or secure.
                        Passengers further understand that any message or information as may be sent to the Website may be
                        read or intercepted by others unless there is a special notice that a particular message (for example,
                        credit card information) is encrypted (sent in code) by an unauthorised third party. Sending a message,
                        email or any communication written or verbal to AirportZo does not cause AirportZo to have any special
                        responsibility to any Passenger.</p>
                    <p>1.22. The booking for Services displayed on the Website may not be available for purchase in any
                        particular country or area. The Services are available at select airports. For details, please refer to
                        www.AirportZo.com/faq. The reference to such Services on the Website does not imply or warrant that
                        the booking of Services will be available at any time in such particular geographical location(s).</p>
                    <p>1.23. The Service and these terms and conditions will be governed by and construed in accordance with
                        the laws of India, and all matters related to the Services and these terms and conditions are subject to
                        the exclusive jurisdiction of the courts at New Delhi.</p>
                    <p><span class="sub__head">2. Online Booking and Passenger(s) Support</span></p>
                    <p>2.1. During the ‘Booking Process’ (available at www.AirportZo.com/service/meet-assist) the Passengers
                        are requested to take extra care while providing information about guest(s), date and time of travel,
                        contact numbers, etc. AirportZo assumes no responsibility whatsoever on account of any problem that
                        may arise on account of false/ erroneous information provided by a Passenger to AirportZo or any delay
                        or cancellation of flight or for any reason whatsoever including any force majeure event/extraordinary
                        circumstance, change in flight schedule, or due to the failure of a Passenger to report at the airport on
                        time.</p>
                    <p>2.2. If any information supplied at the time of booking is found to be incorrect, AirportZo and the Service
                        Providers reserve the right to refuse or reject the provision of the Services. The contact number of the
                        guest, local driver or receiving party must be provided in advance. AirportZo holds no responsibility for
                        incomplete Service fulfilment due to the reason that the given contact number(s) cannot be reached.</p>
                    <p>2.3. Once the Booking Process is completed, the ‘lead passenger’ will receive the booking reference
                        number.</p>
                    <p>2.4. It is hereby clarified that during the Booking Process, if there is any transaction fee / convenience
                        fee which is charged by the payment gateway, bank issuing the credit/debit card, payment wallets, UPI
                        etc. shall be paid by the Passenger and AirportZo shall have no liability to pay such
                        transaction/convenience fee.</p>
                    <p>2.5. The Service will be provided to only those persons who are a part of the booking confirmation and
                        for whom an advance payment has already been made. Any last minute service request for an additional
                        person, who is originally not a part of the booking, will be subject to availability and the final
                        confirmation by the respective Service Provider, and will be subject to spot rates applicable at the
                        airport including surcharge. The payment for the same to be made directly to the respective Service
                        Provider at the airport.</p>
                    <p>2.6. Full rate will be charged for children aged two (2) years old or above.</p>
                    <p>2.7. Children aged twelve (12) and below must be accompanied by an adult aged eighteen (18) and
                        above.</p>
                    <p>2.8. The Service booking is non-transferable and only those Passengers for whom the booking has been
                        done can avail the Service.</p>
                    <p>2.9. The booking confirmation cannot be exchanged for cash or any other promotional program or offers
                        of AirportZo.</p>
                    <p><span class="sub__head">3.Duration of Service</span></p>
                    <p>3.1. The performance of Service will commence at the scheduled meeting time or the time of Service as
                        per the Service confirmation voucher. However, AirportZo/Service Provider, at its sole discretion, may
                        permit Passengers a window of 20 (twenty) minutes from the scheduled meeting time to avail the
                        Service.</p>
                    <p>3.2. In case of any failure of the Passenger to report on time at the meeting point or the time of Service
                        as per the Service confirmation voucher, she/he shall be deemed as a No Show and the Service will not
                        be assured.</p>
                    <p>3.3. Each Service order shall be completed within one (1) hour or at the discretion of the Service
                        Provider in accordance to individual Service package requirements (Service Hours).</p>
                    <p>3.4. Time extension of Service Hours due to guests' own issues, including but not limited to visa
                        problems at immigration, customs clearance or lost baggage, will be subject to a surcharge of an
                        additional fifty (50) percent of the full order amount and subject to availability.</p>
                    <p><span class="sub__head">4. Baggage Policy</span></p>
                    <p>4.1. For Service packages which include the ‘Porter Service’, extra and/ or oversized and/ or overweight
                        baggage will be subject to payment of surcharge, plus any applicable local fees and/ or taxes as
                        follows:5.1.1. Baggage service includes two (2) regular-sized baggage per guest with maximum
                        dimensions of 90 x 75 x 43 cm each, and up to a combined weight of 40kg. Oversized and/ or overweight
                        baggage will be subject to surcharge of INR 200 per piece.</p>
                    <p>4.2. The baggage (including animal carrier) dimensions and weight restrictions provided above are the
                        maximum allowance that can be accepted by Service Providers. Neither AirportZo or the Service
                        Provider guarantees or confirms that such baggage dimensions and/or weight restrictions will be
                        accepted by the airline. It is the sole responsibility of Passengers to ensure that their baggage complies
                        with respective airline restrictions.</p>
                </div>
                <div class="sub__terms-container">
                    <h4>TERMS AND CONDITIONS OF USE OF LOUNGE</h4>
                    <p><span class="sub__head">1. General</span></p>
                    <p>1.1 "Airside/Landside Lounge" means:</p>
                    <p class="sub__list">a) Airside lounge is located in the restricted area. Departing passengers will need to pass
                        through immigration and customs before proceeding to the Airside Lounge. They must obtain a
                        boarding pass for their onward flight. The same is applicable to the transit passengers.</p>
                    <p class="sub__list">b) Landside Lounge is located in the non-restricted area. Arriving passengers can proceed to the
                        Landside Lounge after formalities in immigration, baggage reclaim and customs. Passengers who
                        need to stay in the airport because of early hotel check-out, delayed flight, or other reasons can
                        stay in the Landside Lounge before catching a flight.</p>
                    <p>1.2 "Lounge Facilities" means the provision of awaiting area in Airside/Landside area of the Airport with
                        seating and refreshment facilities including (facilities in different locations may vary):</p>
                    <p class="sub__list">a) Hot showers facilities including amenities</p>
                    <p class="sub__list">b) Food and beverages</p>
                    <p class="sub__list">c) Use of computers to access Internet</p>
                    <p class="sub__list">d) DVD / VCD movie viewing (at selected locations only)</p>
                    <p class="sub__list">e) Selection of local / International magazines and newspapers</p>
                    <p class="sub__list">f) Power and Internet connection for travellers' with laptop computers</p>
                    <p class="sub__list">g) Mobile / laptop battery recharging facilities.</p>
                    <p class="sub__list">h) Telephone for local calls</p>
                    <p class="sub__list">i) Flight Information</p>
                    <p>1.3 "Customer" means the person, firm or company booking the use of Lounge
                        Facilities</p>
                    <p>1.4 "Airport" means the airport from which the Customer is travelling.</p>
                    <p>1.5 "Charges" means the charges paid by the Customer to AirportZo in respect of Lounge Facilities in
                        accordance with AirportZo's charging structure which may be amended by AirportZo from time to
                        time.</p>
                    <p>1.6 The headings in these conditions are for convenience only and shall not affect their interpretation.</p>
                    <p>1.7 Words in the singular shall include the plural and vice versa, references to any gender shall include
                        the other reference to legal persons shall include natural persons and vice versa.</p>
                    <p><span class="sub__head">2. Formation of Contract</span></p>
                    <p>2.1 AirportZo and any third party lounge provider with whom AirportZo has entered into an
                        arrangement for the provision of Lounge Facilities are subject to the terms and conditions of the
                        respective service providers, which the Customer shall indicate and qualify acceptance of by booking the
                        Lounge Facilities and paying the Charges.</p>
                    <p>2.2 No representative, employee or sales person or agent of AirportZo has authority to vary, amend or
                        waive any of these conditions.</p>
                    <p>2.3 These terms and conditions will prevail over any terms or conditions proposed by the Customer
                        orally or on any order form or similar document shall not be binding on AirportZo</p>
                    <p><span class="sub__head">3. Boarding Pass</span></p>
                    <p>3.1 Transit passengers who wish to access the lounge must be in possession of a valid onward boarding
                        pass. Please contact your airline if you require details about obtaining the boarding pass for your
                        transit/connecting flight.</p>
                    <p><span class="sub__head">4. Booking</span></p>
                    <p>4.1 Full payment must be made at the time of booking. Booking is only considered as confirmed when
                        payment has been received by us in full and the booking confirmation email has been sent to the
                        email address provided at the time of booking. It is your responsibility to provide a valid email
                        address.</p>
                    <p>4.2 If a passenger fails to obtain an email confirmation from us, we will NOT be responsible for the
                        availability of service upon passenger's arrival. Passengers without a Confirmation Letter (i.e. not a
                        pre-paid booking) from us will be considered as a "Walk-in" customer. All services requested upon arrival
                        are subject to availability.</p>
                    <p><span class="sub__head">5. Lounge Facilities</span></p>
                    <p>5.1 All specifications, descriptions, drawings, photographs or illustrations of the Lounge Facilities and
                        any advertising matter and sample books are only intended to serve as a guide and not to be relied upon
                        by the Customer or treated as binding or as forming part of these conditions or any contract with the
                        Customer.</p>
                    <p>5.2 AirportZo and any third party lounge provider with whom AirportZo has entered into an
                        arrangement for the provision of Lounge Facilities shall use its reasonable endeavours to provide the
                        Lounge Facilities during the hours advertised for each Airport, but reserves the right to vary the hours of
                        operation or close the lounge due to refurbishment, relocation or otherwise in which case an alternative
                        executive lounge facility will be provided or a refund of the charges will be made at the discretion of
                        AirportZo. In the unlikely event that entry to the Lounge Facilities is refused due to capacity constraints,
                        the Customer will receive a complimentary voucher for their next visit.</p>
                    <p>5.3 AirportZo and any third party lounge provider with whom AirportZo has entered into an
                        arrangement for the provision of Lounge Facilities shall use its reasonable endeavours to ensure a
                        suitable environment is maintained in the Lounge Facilities including but not limited to keeping the area
                        where Lounge Facilities are provided clean and tidy, ensuring staff are on hand to respond to any
                        queries and ensuring the removal from the lounge area of any persons whose behaviour is unsuitable.</p>
                    <p>5.4 AirportZo and any third-party lounge provider with whom AirportZo has entered into an
                        arrangement for the provision of Lounge Facilities shall have the right to refuse a Customer entry to the
                        Lounge Facilities for any Statutory, regulatory or Airport policy reasons including but not limited to
                        health and safety policies or fire regulations.</p>
                    <p>5.5 In order to maintain Customer expectations, children are not permitted to use the Lounge Facilities
                        in certain Lounges. Please check the individual Lounge information on this website for details. In the
                        event that children are permitted access to the Lounge, they should be accompanied in all Lounges
                        Facilities by a Customer over the age of eighteen years at all times.</p>
                    <p><span class="sub__head">6. Charges</span></p>
                    <p>6.1 Charges payable for the Lounge Facilities shall be as stated in AirportZo's services menu (current at
                        the date of booking).</p>
                    <p><span class="sub__head">7. Terms of Payment</span></p>
                    <p>7.1 Customers shall make payment for the Lounge Facilities when booking by entering the details of
                        their PayPal, or debit of credit card onto the online booking form, provided that such credit or debit card
                        is listed as acceptable to AirportZo on the booking form instructions</p>
                    <p>7.2 Unless otherwise agreed in writing, the Customer shall not be entitled to any discount</p>
                    <p><span class="sub__head">8. Customer's Obligations</span></p>
                    <p>8.1 The Customer shall ensure that he is at all times appropriately dressed and shall behave in an
                        appropriate manner. AirportZo and any third party lounge provider with whom AirportZo has entered
                        into an arrangement for the provision of Lounge Facilities reserve the right at their sole and absolute
                        discretion to refuse entry or to remove any customer whose behaviour or mode of dress is considered
                        by AirportZo to be unsuitable or is likely to offend other Customers.</p>
                    <p>8.2 Customers must not remove food and/or drinks from the Lounge Facilities and will be asked to
                        refrain from consuming food and/or drinks in the Lounge Facilities other than food and/or drinks
                        provided in the Lounge Facilities.</p>
                    <p>8.3 The Customer agrees to adhere to any no smoking policies in operation in any of the Lounge
                        Facilities.</p>
                    <p>8.4 Customers shall provide a minimum of 72 hours’ written notice to AirportZo in the event of
                        cancellation of a group booking. A group booking is a booking of 10 or more persons or 5 or more
                        rooms. No refund will be arranged for cancellation made within 72 hours prior to the reserved service
                        date and time. All refunds / changes made on a confirmed group booking are subject to a minimum of
                        Rs. 1000/- administration fee per person.</p>
                    <p>8.5 In the event of cancellation of bookings for Private Resting Area, Transit Hotel Room and/or Aerotel
                        Room services, customers agree to provide a minimum of 24 hours' written notice to AirportZo. No
                        refund will be arranged for cancellations made within 24 hours prior to the reserved service date and
                        time. All refunds/changes made on a confirmed Private Resting Area and/or Transit Hotel Room booking
                        are subject to a minimum administration fee of Rs.1000/- per person or 25% of the total booking
                        amount, whichever is higher</p>
                    <p>8.6 For all other bookings not covered in Clause 8.5, a cancellation fee of Rs.1000/- per person will be
                        charged for all bookings cancelled within 12 hours prior to the booking. No-show or last-minute
                        cancellations with less than 12 hours' notice will be non-refundable.</p>
                    <p>8.7 In the event of a customer wishing to amend an existing booking to a later date and/or at any
                        Airport where AirportZo operates Lounge Facilities at a later date, provided that AirportZo receives from
                        the Customer at least 24 hours prior written notice of a cancellation of a booking for Lounge Services
                        from the Customer, AirportZo agrees to provide access to Lounge Facilities to the same number of users
                        as on the original booking, at a later date at any Airport where AirportZo and any third party lounge
                        provider with whom AirportZo has entered into an arrangement for the provision of Lounge Facilities
                        ("Alternative Lounge Facilities"),subject to prior receipt by AirportZo from the Customer of (i)
                        confirmation of the date and/or Airport Lounge Facilities required; (ii) a payment of Rs. 1000/- per
                        person per booking; and (iii) the difference between the Charges paid by the Customer in relation to the
                        original booking and the charges in respect of the Alternative Lounge Facilities applicable as at the
                        proposed date of use of such Alternative Lounge Facilities (whether the Alternative Lounge Facilities are
                        located at the same Airport as on the original booking for Lounge Facilities or otherwise).</p>
                    <p><span class="sub__head">9. Limitation Liability</span></p>
                    <p>9.1 Subject to clause 9.2, AirportZo and any third party lounge provider with whom AirportZo has
                        entered into an arrangement for the provision of Lounge Facilities shall under no circumstances be liable
                        for any indirect, special or consequential loss, including but not limited to loss of profit, loss of contract,
                        loss of revenue or loss of business, however arising whether in contract, tort (including negligence) or
                        statutory duty or otherwise.</p>
                    <p>9.2 AirportZo and any third party lounge provider with whom AirportZo has entered into an
                        arrangement for the provision of Lounge Facilities does not exclude loss arising from death or personal
                        injury caused by negligence.</p>
                    <p>9.3 Subject to clause 9.2 above, the aggregate liability of AirportZo and any third party lounge provider
                        with whom AirportZo has entered into an arrangement for the provision of Lounge Facilities, (whether
                        in contract, tort (including negligence) or breach of statutory duty or otherwise) to no circumstances
                        shall exceed the Charges paid by the Customer for the Lounge Facilities.</p>
                    <p>9.4 AirportZo and any third party lounge provider with whom AirportZo has entered into an
                        arrangement for the provision of Lounge Facilities shall under no circumstances be liable for any
                        Customer failing to board his flight and neither AirportZo nor any third party lounge provider with whom
                        AirportZo has entered into an arrangement for the provision of Lounge Facilities has any obligation to
                        make flight announcements.</p>
                    <p>9.5 AirportZo and any third party lounge provider with whom AirportZo has entered into an
                        arrangement for the provision of Lounge Facilities shall under no circumstances be liable or responsible
                        for the personal belongings of any Customer, and a Customer shall take personal belongings into the
                        Lounge Facilities area solely at his own risk.</p>
                    <p>9.6 All information, recommendations and advice given by or on behalf of AirportZo and any third party
                        lounge provider with whom AirportZo has entered into an arrangement for the provision of Lounge
                        Facilities to the Customer regarding Airport services or flight details are given without liability on the
                        part of AirportZo.</p>
                    <p>9.7 The Customer shall fully indemnify and compensate AirportZo and any third party lounge provider
                        with whom AirportZo has entered into an arrangement for the provision of Lounge Facilities, its
                        employees, sub-contractors and agents in respect of all actions, suits, claims, demands, costs, charges or
                        expenses arising (whether asserted by the Customer or third party) out of or in connection with the
                        provision of theLounge Facilities which:</p>
                    <p class="sub__list">a) are in excess of AirportZo's liability set out in clause 9.3 above; and</p>
                    <p class="sub__list">b) are caused directly or indirectly through the act or omission, wilful misconduct or negligence
                        of the Customer.</p>
                    <p><span class="sub__head">10. Force Majeure</span></p>
                    <p>10.1 AirportZo and any third party lounge provider with whom AirportZo has entered into an
                        arrangement for the provision of Lounge Facilities shall not be liable to the Customer for any loss or
                        damage caused to or suffered by the Customer as a direct or indirect result of the provision of the
                        Lounge Facilities by or on behalf of AirportZo being prevented, restricted, hindered or delayed by reason
                        of any circumstances outside the control of AirportZo.</p>
                    <p><span class="sub__head">11. Waiver</span></p>
                    <p>11.1 The right powers and remedies provided pursuant to these conditions are cumulative and do not
                        exclude or affect any rights, powers or remedies provided by law. No delay in exercising, or non
                        exercising by AirportZo of any rights or remedies under these conditions shall operate as a waiver or
                        lease of that right, power or remedy.</p>
                    <p><span class="sub__head">12. Variation</span></p>
                    <p>12.1 No amendments or variation of these conditions shall be effective unless made in writing and
                        signed or issued by AirportZo.</p>
                    <p><span class="sub__head">13. Governing Law</span></p>
                    <p>13.1 These conditions shall be construed in accordance with Indian Laws and AirportZo and the
                        Customer hereby submit to the exclusive jurisdiction of the courts of India.</p>
                </div>
                <div class="terms__footer">
                    <strong>Terms & conditions | Privacy & cookies policy</strong>
                    <p>Please do not reply to this email as it is an automated email and cannot be responded to.
                        AirportZo will NEVER contact you via phone or email asking to verify your password/PIN or user
                        ID. All rights reserved.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- ========== FOOTER ========== -->
    <footer class="footer"></footer>

    <!-- ================  MODALS ================ -->
    <!-- LOGIN MODAL -->
    <div id="login_modal" class="modal fade" role="dialog"></div>

    <script src='js/jquery.min.js'></script>
    <script src="js/bootstrap.min.3.3.5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
    <script src="js/main.js<?php echo $cache_str; ?>"></script>
    <script src="js/cart.js<?php echo $cache_str; ?>"></script>
</body>

</html>