<?php
// ini_set('display_errors', 1);// show error reporting
// error_reporting(E_ALL);
include 'invoice.php';

$data ='{
    "distributor_name": "",
    "distributor_email": "",
    "header_logo": "",
    "brand_colour": "",
    "id": "1839",
    "token": "2907910175",
    "booking_number": "723240146859",
    "user_token": "9573111958",
    "user_name": "Praveenraj",
    "user_mobile": "+918667533026",
    "user_image": "",
    "user_email": "praveen@gmail.com",
    "for_others": false,
    "journey": "MAA - BLR - DXB - AMS",
    "service_amount": "98262",
    "service_gst": "17687",
    "convenience_fee": "3512",
    "cf_tax": "632",
    "total_amount": "120093",
    "currency": "INR",
    "payment_view": "120093.00",
    "discount_type": "2",
    "coupon_type": "1",
    "discount_amount": "6272",
    "coupon_token": "4Y9ZNB6HA2",
    "total_service": "8",
    "total_adult": "2",
    "total_children": "2",
    "service_dates": [
        "30 Jan 2023"
    ],
    "type": "INR",
    "booking_type": "Web",
    "date_time": "29 Jan 2023",
    "status": "Pending",
    "e_ticket": "https://d1xqjehqvi7b4u.cloudfront.net/user/e_ticket/1674980351000.pdf",
    "pancard_number": "",
    "gst_name": "",
    "gst_number": "",
    "description_one": "",
    "description_two": "",
    "payment_id": "pay_L9vLf6odAl3DYT",
    "invoice_pdf": "https://airportzostage.in/invoice_pdf/2907910175.pdf",
    "airportzo_cancel_fee": "150",
    "service_distributor_token": "1111111111",
    "order_detail": [
        {
            "airport_token": "2243597708",
            "gmt_view": "+05:30",
            "airport_name": "Chennai International Airport",
            "airport_code": "MAA",
            "terminal_token": "9876543210",
            "terminal_name": "Terminal 1",
            "station_number": 1,
            "order_detail_array": [
                {
                    "id": "3400",
                    "token": "2120302070",
                    "booking_token": "2907910175",
                    "airport_token": "2243597708",
                    "airport_name": "Chennai International Airport",
                    "airport_code": "MAA",
                    "terminal_token": "9876543210",
                    "terminal_name": "Terminal 1",
                    "company_token": "8191432180",
                    "company_name": "Pravin Lounge",
                    "company_email": "pravinmichal@gmail.com",
                    "company_logo": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1663670541313.png",
                    "company_image": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1663670829844.png",
                    "station_number": 1,
                    "flight_number": "",
                    "airport_type": "7424792131",
                    "airport_category": "1122334456",
                    "service_date_time": "30 Jan, 2023 14:00",
                    "service_date": "30 Jan, 2023",
                    "service_time": "02:00 PM",
                    "service_date_time_raw": "2023-01-30 14:00:00",
                    "service_token": "2OVKIAGUFX",
                    "service_name": "Domestic-Arrival-Porter",
                    "service_type": "Bundle",
                    "service_location_token": "1KS0CAMLDP",
                    "journey_date": "-",
                    "journey": "",
                    "date_time": "2023-01-29 08:19:33",
                    "status": "Pending",
                    "adult_service_amount": "2875",
                    "total_adult": "2",
                    "children_service_amount": "1800",
                    "total_children": "2",
                    "net_amount": "9350",
                    "notes": "",
                    "rating": "0",
                    "review": "",
                    "review_date_time": "30 Nov, -0001",
                    "comment": "",
                    "comment_date_time": "-",
                    "description": "",
                    "report_reason_token": "",
                    "report_reason": "",
                    "report_description": "",
                    "reported_date_time": "30 Nov,-0001 12:00 AM",
                    "cancellation_policy_detail": [
                        {
                            "hours": "24",
                            "percentage": "30"
                        }
                    ],
                    "reschedule_policy": "policy details click here",
                    "can_be_cancelled": true,
                    "cancelled_by": "",
                    "cancellation_detail": {
                        "cancellation_hours": "24",
                        "cancellation_fee": "2805.00",
                        "cancellation_fee_perc": "30",
                        "airportzo_fee": "150",
                        "max_airportzo_fee": "150",
                        "cancelled_date": "-",
                        "refund_amount": "6395",
                        "refund_status": "Pending",
                        "refunded_date": "-",
                        "service_cost": "9350"
                    },
                    "az_sp_commision_amount": "0",
                    "sp_balance_credit": "-787684",
                    "currency": "INR",
                    "markup_amount": "0",
                    "discount_amount": "0",
                    "is_coupon_service": "0",
                    "cart_coupon_type": "Excl Gst",
                    "discount": "6272",
                    "totalAdult_pdf": 1,
                    "total_additionalAdult_pdf": 1,
                    "totalChildren_pdf": 1,
                    "total_additionalChildren_pdf": 1,
                    "adult_serv_amt": 2436,
                    "child_serv_amt": 1525,
                    "add_adult_service_amount": 2436,
                    "add_children_service_amount": 1525,
                    "adult_discount": 146,
                    "child_discount": 92,
                    "add_adult_discount": 146,
                    "add_child_discount": 92,
                    "adult_net_amt": 2290,
                    "child_net_amt": 1433,
                    "add_adult_net_amt": 2290,
                    "add_child_net_amt": 1433,
                    "tax_rate1": "9% CGST",
                    "tax_rate2": "9% SGST",
                    "adult_tax_amt1": "206",
                    "adult_tax_amt2": "206",
                    "child_tax_amt1": "129",
                    "child_tax_amt2": "129",
                    "add_adult_tax_amt1": "206",
                    "add_adult_tax_amt2": "206",
                    "add_child_tax_amt1": "129",
                    "add_child_tax_amt2": "129",
                    "adult_sub_total": 2702,
                    "child_sub_total": 1691,
                    "add_adult_sub_total": 2702,
                    "add_child_sub_total": 1691,
                    "tax_type": 2,
                    "gst_no": "33AACCF8045D1ZM",
                    "place_serv": "Tamil Nadu",
                    "ut_code": "25",
                    "num_count": 8,
                    "max": "11500",
                    "ext_gst_serv_amt": 104528
                },
                {
                    "id": "3401",
                    "token": "8318932446",
                    "booking_token": "2907910175",
                    "airport_token": "2243597708",
                    "airport_name": "Chennai International Airport",
                    "airport_code": "MAA",
                    "terminal_token": "9876543210",
                    "terminal_name": "Terminal 1",
                    "company_token": "1824363970",
                    "company_name": "Encalm",
                    "company_email": "jegan@macappstudio.com",
                    "company_logo": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1665657082180.jpg",
                    "company_image": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1665657103902.jpg",
                    "station_number": 1,
                    "flight_number": "",
                    "airport_type": "7424792131",
                    "airport_category": "1122334456",
                    "service_date_time": "30 Jan, 2023 14:00",
                    "service_date": "30 Jan, 2023",
                    "service_time": "02:00 PM",
                    "service_date_time_raw": "2023-01-30 14:00:00",
                    "service_token": "7YRQGW28MD",
                    "service_name": "Domestic-Departure-Chauffeur",
                    "service_type": "Individual",
                    "service_location_token": "FR318QJMI6",
                    "journey_date": "-",
                    "journey": "",
                    "date_time": "2023-01-29 08:19:33",
                    "status": "Pending",
                    "adult_service_amount": "300",
                    "total_adult": "2",
                    "children_service_amount": "300",
                    "total_children": "2",
                    "net_amount": "1200",
                    "notes": "",
                    "rating": "0",
                    "review": "",
                    "review_date_time": "30 Nov, -0001",
                    "comment": "",
                    "comment_date_time": "-",
                    "description": "",
                    "report_reason_token": "",
                    "report_reason": "",
                    "report_description": "",
                    "reported_date_time": "30 Nov,-0001 12:00 AM",
                    "cancellation_policy_detail": [
                        {
                            "hours": "48",
                            "percentage": "0"
                        },
                        {
                            "hours": "36",
                            "percentage": "25"
                        },
                        {
                            "hours": "24",
                            "percentage": "50"
                        },
                        {
                            "hours": "12",
                            "percentage": "75"
                        }
                    ],
                    "reschedule_policy": "Re-Schedule Policy\nRe-Schedule Policy",
                    "can_be_cancelled": true,
                    "cancelled_by": "",
                    "cancellation_detail": {
                        "cancellation_hours": "24",
                        "cancellation_fee": "600.00",
                        "cancellation_fee_perc": "50",
                        "airportzo_fee": "150",
                        "max_airportzo_fee": "150",
                        "cancelled_date": "-",
                        "refund_amount": "450",
                        "refund_status": "Pending",
                        "refunded_date": "-",
                        "service_cost": "1200"
                    },
                    "az_sp_commision_amount": "120",
                    "sp_balance_credit": "-6086.3",
                    "currency": "INR",
                    "markup_amount": "0",
                    "discount_amount": "0",
                    "is_coupon_service": "0",
                    "cart_coupon_type": "Excl Gst",
                    "discount": "6272",
                    "totalAdult_pdf": 1,
                    "total_additionalAdult_pdf": 1,
                    "totalChildren_pdf": 1,
                    "total_additionalChildren_pdf": 1,
                    "adult_serv_amt": 254,
                    "child_serv_amt": 254,
                    "add_adult_service_amount": 254,
                    "add_children_service_amount": 254,
                    "adult_discount": 15,
                    "child_discount": 15,
                    "add_adult_discount": 15,
                    "add_child_discount": 15,
                    "adult_net_amt": 239,
                    "child_net_amt": 239,
                    "add_adult_net_amt": 239,
                    "add_child_net_amt": 239,
                    "tax_rate1": "9% CGST",
                    "tax_rate2": "9% SGST",
                    "adult_tax_amt1": "22",
                    "adult_tax_amt2": "22",
                    "child_tax_amt1": "22",
                    "child_tax_amt2": "22",
                    "add_adult_tax_amt1": "22",
                    "add_adult_tax_amt2": "22",
                    "add_child_tax_amt1": "22",
                    "add_child_tax_amt2": "22",
                    "adult_sub_total": 283,
                    "child_sub_total": 283,
                    "add_adult_sub_total": 283,
                    "add_child_sub_total": 283,
                    "tax_type": 2,
                    "gst_no": "33AACCF8045D1ZM",
                    "place_serv": "Tamil Nadu",
                    "ut_code": "25",
                    "num_count": 8,
                    "max": "11500",
                    "ext_gst_serv_amt": 104528
                },
                {
                    "id": "3402",
                    "token": "5674908438",
                    "booking_token": "2907910175",
                    "airport_token": "2243597708",
                    "airport_name": "Chennai International Airport",
                    "airport_code": "MAA",
                    "terminal_token": "9876543210",
                    "terminal_name": "Terminal 1",
                    "company_token": "8058283657",
                    "company_name": "Sleepzzzo",
                    "company_email": "adhi@macappstudio.com",
                    "company_logo": "https://d1kbhg7ykrtfl2.cloudfront.net/service_provider_company/company_logo/sleepzzzo_logo.png",
                    "company_image": "https://d1kbhg7ykrtfl2.cloudfront.net/service_provider_company/company_logo/Sleepzzzo.jpg",
                    "station_number": 1,
                    "flight_number": "",
                    "airport_type": "7424792131",
                    "airport_category": "1122334456",
                    "service_date_time": "30 Jan, 2023 14:00",
                    "service_date": "30 Jan, 2023",
                    "service_time": "02:00 PM",
                    "service_date_time_raw": "2023-01-30 14:00:00",
                    "service_token": "LHYU85QMZE",
                    "service_name": "Domestic-Departure-Elite (With Lounge)",
                    "service_type": "Individual",
                    "service_location_token": "RYQ09P7LJ4",
                    "journey_date": "-",
                    "journey": "",
                    "date_time": "2023-01-29 08:19:33",
                    "status": "Pending",
                    "adult_service_amount": "2875",
                    "total_adult": "2",
                    "children_service_amount": "2875",
                    "total_children": "2",
                    "net_amount": "11500",
                    "notes": "",
                    "rating": "0",
                    "review": "",
                    "review_date_time": "30 Nov, -0001",
                    "comment": "",
                    "comment_date_time": "-",
                    "description": "",
                    "report_reason_token": "",
                    "report_reason": "",
                    "report_description": "",
                    "reported_date_time": "30 Nov,-0001 12:00 AM",
                    "cancellation_policy_detail": [
                        {
                            "hours": "11",
                            "percentage": "21"
                        },
                        {
                            "hours": "24",
                            "percentage": "43"
                        },
                        {
                            "hours": "32",
                            "percentage": "32"
                        },
                        {
                            "hours": "55",
                            "percentage": "54"
                        },
                        {
                            "hours": "1",
                            "percentage": "2"
                        },
                        {
                            "hours": "28",
                            "percentage": "99"
                        },
                        {
                            "hours": "3",
                            "percentage": "7"
                        },
                        {
                            "hours": "5",
                            "percentage": "5"
                        },
                        {
                            "hours": "7",
                            "percentage": "77"
                        },
                        {
                            "hours": "2",
                            "percentage": "127"
                        },
                        {
                            "hours": "9",
                            "percentage": "97"
                        },
                        {
                            "hours": "0",
                            "percentage": "0"
                        },
                        {
                            "hours": "44",
                            "percentage": "127"
                        },
                        {
                            "hours": "54",
                            "percentage": "127"
                        }
                    ],
                    "reschedule_policy": "Give a brief about your shop Give a brief about your shopGive a brief about your shopGive a brief about your shopGive a brief about your shopGive a brief about your shopGive a brief about your shopGive a brief about your shopGive a brief about your shopGive a brief about your shop",
                    "can_be_cancelled": true,
                    "cancelled_by": "",
                    "cancellation_detail": {
                        "cancellation_hours": "0",
                        "cancellation_fee": "0.00",
                        "cancellation_fee_perc": "0",
                        "airportzo_fee": "150",
                        "max_airportzo_fee": "150",
                        "cancelled_date": "-",
                        "refund_amount": "11350",
                        "refund_status": "Pending",
                        "refunded_date": "-",
                        "service_cost": "11500"
                    },
                    "az_sp_commision_amount": "0",
                    "sp_balance_credit": "-4079230",
                    "currency": "INR",
                    "markup_amount": "0",
                    "discount_amount": "0",
                    "is_coupon_service": "0",
                    "cart_coupon_type": "Excl Gst",
                    "discount": "6272",
                    "totalAdult_pdf": 1,
                    "total_additionalAdult_pdf": 1,
                    "totalChildren_pdf": 1,
                    "total_additionalChildren_pdf": 1,
                    "adult_serv_amt": 2436,
                    "child_serv_amt": 2436,
                    "add_adult_service_amount": 2436,
                    "add_children_service_amount": 2436,
                    "adult_discount": 146,
                    "child_discount": 146,
                    "add_adult_discount": 146,
                    "add_child_discount": 146,
                    "adult_net_amt": 2290,
                    "child_net_amt": 2290,
                    "add_adult_net_amt": 2290,
                    "add_child_net_amt": 2290,
                    "tax_rate1": "9% CGST",
                    "tax_rate2": "9% SGST",
                    "adult_tax_amt1": "206",
                    "adult_tax_amt2": "206",
                    "child_tax_amt1": "206",
                    "child_tax_amt2": "206",
                    "add_adult_tax_amt1": "206",
                    "add_adult_tax_amt2": "206",
                    "add_child_tax_amt1": "206",
                    "add_child_tax_amt2": "206",
                    "adult_sub_total": 2702,
                    "child_sub_total": 2702,
                    "add_adult_sub_total": 2702,
                    "add_child_sub_total": 2702,
                    "tax_type": 2,
                    "gst_no": "33AACCF8045D1ZM",
                    "place_serv": "Tamil Nadu",
                    "ut_code": "25",
                    "num_count": 8,
                    "max": "11500",
                    "ext_gst_serv_amt": 104528
                }
            ],
            "airport_type": "Departure",
            "flight_number": "ewds"
        },
        {
            "airport_token": "5098210235",
            "gmt_view": "+05:30",
            "airport_name": "Kempegowda International Airport",
            "airport_code": "BLR",
            "terminal_token": "9876543210",
            "terminal_name": "Terminal 1",
            "station_number": 2,
            "order_detail_array": [
                {
                    "id": "3403",
                    "token": "9858897054",
                    "booking_token": "2907910175",
                    "airport_token": "5098210235",
                    "airport_name": "Kempegowda International Airport",
                    "airport_code": "BLR",
                    "terminal_token": "9876543210",
                    "terminal_name": "Terminal 1",
                    "company_token": "2318241160",
                    "company_name": "Pravin marhaba",
                    "company_email": "pravin@macappstudio.com",
                    "company_logo": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1665741398140.jpg",
                    "company_image": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1665741401209.jpg",
                    "station_number": 2,
                    "flight_number": "",
                    "airport_type": "8450793000",
                    "airport_category": "1122334457",
                    "service_date_time": "30 Jan, 2023 15:00",
                    "service_date": "30 Jan, 2023",
                    "service_time": "03:00 PM",
                    "service_date_time_raw": "2023-01-30 15:00:00",
                    "service_token": "YG8UK12EIP",
                    "service_name": "Domestic-International-Transit-Silver (Without Lounge)",
                    "service_type": "Bundle",
                    "service_location_token": "LU0FCQ8V9B",
                    "journey_date": "-",
                    "journey": "",
                    "date_time": "2023-01-29 08:19:33",
                    "status": "Pending",
                    "adult_service_amount": "5310",
                    "total_adult": "2",
                    "children_service_amount": "5310",
                    "total_children": "2",
                    "net_amount": "20820",
                    "notes": "",
                    "rating": "0",
                    "review": "",
                    "review_date_time": "30 Nov, -0001",
                    "comment": "",
                    "comment_date_time": "-",
                    "description": "",
                    "report_reason_token": "",
                    "report_reason": "",
                    "report_description": "",
                    "reported_date_time": "30 Nov,-0001 12:00 AM",
                    "cancellation_policy_detail": [
                        {
                            "hours": "48",
                            "percentage": "10"
                        },
                        {
                            "hours": "24",
                            "percentage": "20"
                        }
                    ],
                    "reschedule_policy": "Contact support@airportzo.com",
                    "can_be_cancelled": true,
                    "cancelled_by": "",
                    "cancellation_detail": {
                        "cancellation_hours": "24",
                        "cancellation_fee": "4164.00",
                        "cancellation_fee_perc": "20",
                        "airportzo_fee": "150",
                        "max_airportzo_fee": "150",
                        "cancelled_date": "-",
                        "refund_amount": "16506",
                        "refund_status": "Pending",
                        "refunded_date": "-",
                        "service_cost": "20820"
                    },
                    "az_sp_commision_amount": "1041",
                    "sp_balance_credit": "23984400",
                    "currency": "INR",
                    "markup_amount": "0",
                    "discount_amount": "0",
                    "is_coupon_service": "0",
                    "cart_coupon_type": "Excl Gst",
                    "discount": "6272",
                    "totalAdult_pdf": 1,
                    "total_additionalAdult_pdf": 1,
                    "totalChildren_pdf": 1,
                    "total_additionalChildren_pdf": 1,
                    "adult_serv_amt": 4500,
                    "child_serv_amt": 4500,
                    "add_adult_service_amount": 4322,
                    "add_children_service_amount": 4322,
                    "adult_discount": 270,
                    "child_discount": 270,
                    "add_adult_discount": 259,
                    "add_child_discount": 259,
                    "adult_net_amt": 4230,
                    "child_net_amt": 4230,
                    "add_adult_net_amt": 4063,
                    "add_child_net_amt": 4063,
                    "tax_rate1": "9% CGST",
                    "tax_rate2": "9% SGST",
                    "adult_tax_amt1": "381",
                    "adult_tax_amt2": "381",
                    "child_tax_amt1": "381",
                    "child_tax_amt2": "381",
                    "add_adult_tax_amt1": "366",
                    "add_adult_tax_amt2": "366",
                    "add_child_tax_amt1": "366",
                    "add_child_tax_amt2": "366",
                    "adult_sub_total": 4992,
                    "child_sub_total": 4992,
                    "add_adult_sub_total": 4795,
                    "add_child_sub_total": 4795,
                    "tax_type": 2,
                    "gst_no": "33AACCF8045D1ZM",
                    "place_serv": "Tamil Nadu",
                    "ut_code": "25",
                    "num_count": 8,
                    "max": "11500",
                    "ext_gst_serv_amt": 104528
                },
                {
                    "id": "3404",
                    "token": "2710912191",
                    "booking_token": "2907910175",
                    "airport_token": "5098210235",
                    "airport_name": "Kempegowda International Airport",
                    "airport_code": "BLR",
                    "terminal_token": "9876543210",
                    "terminal_name": "Terminal 1",
                    "company_token": "2318241160",
                    "company_name": "Pravin marhaba",
                    "company_email": "pravin@macappstudio.com",
                    "company_logo": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1665741398140.jpg",
                    "company_image": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1665741401209.jpg",
                    "station_number": 2,
                    "flight_number": "",
                    "airport_type": "8450793000",
                    "airport_category": "1122334457",
                    "service_date_time": "30 Jan, 2023 15:00",
                    "service_date": "30 Jan, 2023",
                    "service_time": "03:00 PM",
                    "service_date_time_raw": "2023-01-30 15:00:00",
                    "service_token": "RCMWVT9X7B",
                    "service_name": "Domestic-International-Transit-Silver (Without Lounge)",
                    "service_type": "Bundle",
                    "service_location_token": "RP7FQZABWD",
                    "journey_date": "-",
                    "journey": "",
                    "date_time": "2023-01-29 08:19:33",
                    "status": "Pending",
                    "adult_service_amount": "5310",
                    "total_adult": "2",
                    "children_service_amount": "5310",
                    "total_children": "2",
                    "net_amount": "21240",
                    "notes": "",
                    "rating": "0",
                    "review": "",
                    "review_date_time": "30 Nov, -0001",
                    "comment": "",
                    "comment_date_time": "-",
                    "description": "",
                    "report_reason_token": "",
                    "report_reason": "",
                    "report_description": "",
                    "reported_date_time": "30 Nov,-0001 12:00 AM",
                    "cancellation_policy_detail": [
                        {
                            "hours": "48",
                            "percentage": "10"
                        },
                        {
                            "hours": "24",
                            "percentage": "20"
                        }
                    ],
                    "reschedule_policy": "Contact support@airportzo.com",
                    "can_be_cancelled": true,
                    "cancelled_by": "",
                    "cancellation_detail": {
                        "cancellation_hours": "24",
                        "cancellation_fee": "4248.00",
                        "cancellation_fee_perc": "20",
                        "airportzo_fee": "150",
                        "max_airportzo_fee": "150",
                        "cancelled_date": "-",
                        "refund_amount": "16842",
                        "refund_status": "Pending",
                        "refunded_date": "-",
                        "service_cost": "21240"
                    },
                    "az_sp_commision_amount": "1062",
                    "sp_balance_credit": "23964200",
                    "currency": "INR",
                    "markup_amount": "0",
                    "discount_amount": "0",
                    "is_coupon_service": "0",
                    "cart_coupon_type": "Excl Gst",
                    "discount": "6272",
                    "totalAdult_pdf": 1,
                    "total_additionalAdult_pdf": 1,
                    "totalChildren_pdf": 1,
                    "total_additionalChildren_pdf": 1,
                    "adult_serv_amt": 4500,
                    "child_serv_amt": 4500,
                    "add_adult_service_amount": 4500,
                    "add_children_service_amount": 4500,
                    "adult_discount": 270,
                    "child_discount": 270,
                    "add_adult_discount": 270,
                    "add_child_discount": 270,
                    "adult_net_amt": 4230,
                    "child_net_amt": 4230,
                    "add_adult_net_amt": 4230,
                    "add_child_net_amt": 4230,
                    "tax_rate1": "9% CGST",
                    "tax_rate2": "9% SGST",
                    "adult_tax_amt1": "381",
                    "adult_tax_amt2": "381",
                    "child_tax_amt1": "381",
                    "child_tax_amt2": "381",
                    "add_adult_tax_amt1": "381",
                    "add_adult_tax_amt2": "381",
                    "add_child_tax_amt1": "381",
                    "add_child_tax_amt2": "381",
                    "adult_sub_total": 4992,
                    "child_sub_total": 4992,
                    "add_adult_sub_total": 4992,
                    "add_child_sub_total": 4992,
                    "tax_type": 2,
                    "gst_no": "33AACCF8045D1ZM",
                    "place_serv": "Tamil Nadu",
                    "ut_code": "25",
                    "num_count": 8,
                    "max": "11500",
                    "ext_gst_serv_amt": 104528
                },
                {
                    "id": "3405",
                    "token": "8419022210",
                    "booking_token": "2907910175",
                    "airport_token": "5098210235",
                    "airport_name": "Kempegowda International Airport",
                    "airport_code": "BLR",
                    "terminal_token": "9876543210",
                    "terminal_name": "Terminal 1",
                    "company_token": "6551130179",
                    "company_name": "Jeyakumar",
                    "company_email": "pravin@macappstudio.com",
                    "company_logo": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1674817719051.jpg",
                    "company_image": "https://d1xqjehqvi7b4u.cloudfront.net/service_provider_company/documents/1674817723120.jpg",
                    "station_number": 2,
                    "flight_number": "",
                    "airport_type": "8450793000",
                    "airport_category": "1122334457",
                    "service_date_time": "30 Jan, 2023 15:00",
                    "service_date": "30 Jan, 2023",
                    "service_time": "03:00 PM",
                    "service_date_time_raw": "2023-01-30 15:00:00",
                    "service_token": "JF0THMD87G",
                    "service_name": "Domestic-International-Transit-Hotel",
                    "service_type": "Individual",
                    "service_location_token": "XDVKA1CE76",
                    "journey_date": "-",
                    "journey": "",
                    "date_time": "2023-01-29 08:19:33",
                    "status": "Pending",
                    "adult_service_amount": "700",
                    "total_adult": "2",
                    "children_service_amount": "700",
                    "total_children": "2",
                    "net_amount": "2400",
                    "notes": "",
                    "rating": "0",
                    "review": "",
                    "review_date_time": "30 Nov, -0001",
                    "comment": "",
                    "comment_date_time": "-",
                    "description": "",
                    "report_reason_token": "",
                    "report_reason": "",
                    "report_description": "",
                    "reported_date_time": "30 Nov,-0001 12:00 AM",
                    "cancellation_policy_detail": [
                        {
                            "hours": "48",
                            "percentage": "10"
                        },
                        {
                            "hours": "24",
                            "percentage": "90"
                        }
                    ],
                    "reschedule_policy": "support@airportzo.com",
                    "can_be_cancelled": true,
                    "cancelled_by": "",
                    "cancellation_detail": {
                        "cancellation_hours": "24",
                        "cancellation_fee": "2160.00",
                        "cancellation_fee_perc": "90",
                        "airportzo_fee": "150",
                        "max_airportzo_fee": "150",
                        "cancelled_date": "-",
                        "refund_amount": "90",
                        "refund_status": "Pending",
                        "refunded_date": "-",
                        "service_cost": "2400"
                    },
                    "az_sp_commision_amount": "240",
                    "sp_balance_credit": "-24720.7",
                    "currency": "INR",
                    "markup_amount": "0",
                    "discount_amount": "0",
                    "is_coupon_service": "0",
                    "cart_coupon_type": "Excl Gst",
                    "discount": "6272",
                    "totalAdult_pdf": 1,
                    "total_additionalAdult_pdf": 1,
                    "totalChildren_pdf": 1,
                    "total_additionalChildren_pdf": 1,
                    "adult_serv_amt": 593,
                    "child_serv_amt": 593,
                    "add_adult_service_amount": 424,
                    "add_children_service_amount": 424,
                    "adult_discount": 36,
                    "child_discount": 36,
                    "add_adult_discount": 25,
                    "add_child_discount": 25,
                    "adult_net_amt": 557,
                    "child_net_amt": 557,
                    "add_adult_net_amt": 399,
                    "add_child_net_amt": 399,
                    "tax_rate1": "9% CGST",
                    "tax_rate2": "9% SGST",
                    "adult_tax_amt1": "50",
                    "adult_tax_amt2": "50",
                    "child_tax_amt1": "50",
                    "child_tax_amt2": "50",
                    "add_adult_tax_amt1": "36",
                    "add_adult_tax_amt2": "36",
                    "add_child_tax_amt1": "36",
                    "add_child_tax_amt2": "36",
                    "adult_sub_total": 657,
                    "child_sub_total": 657,
                    "add_adult_sub_total": 471,
                    "add_child_sub_total": 471,
                    "tax_type": 2,
                    "gst_no": "33AACCF8045D1ZM",
                    "place_serv": "Tamil Nadu",
                    "ut_code": "25",
                    "num_count": 8,
                    "max": "11500",
                    "ext_gst_serv_amt": 104528
                }
            ],
            "airport_type": "Transit",
            "flight_number": "ewds,sd"
        },
        {
            "airport_token": "3219038277",
            "gmt_view": "+04:00",
            "airport_name": "Dubai International Airport",
            "airport_code": "DXB",
            "terminal_token": "9876543210",
            "terminal_name": "Terminal 1",
            "station_number": 3,
            "order_detail_array": [
                {
                    "id": "3406",
                    "token": "4403526427",
                    "booking_token": "2907910175",
                    "airport_token": "3219038277",
                    "airport_name": "Dubai International Airport",
                    "airport_code": "DXB",
                    "terminal_token": "9876543210",
                    "terminal_name": "Terminal 1",
                    "company_token": "6097245962",
                    "company_name": "Ahlan",
                    "company_email": "vetrikumar@airportzo.com",
                    "company_logo": "https://d1kbhg7ykrtfl2.cloudfront.net/service_provider_company/company_logo/ahlan.jpg",
                    "company_image": "https://d1kbhg7ykrtfl2.cloudfront.net/service_provider_company/company_logo/Ahlan_image.png",
                    "station_number": 3,
                    "flight_number": "",
                    "airport_type": "2260613245",
                    "airport_category": "1122334457",
                    "service_date_time": "30 Jan, 2023 16:00",
                    "service_date": "30 Jan, 2023",
                    "service_time": "04:00 PM",
                    "service_date_time_raw": "2023-01-30 16:00:00",
                    "service_token": "ML5ZIG7SDO",
                    "service_name": "International-Transit-Buggy Transfer",
                    "service_type": "Individual",
                    "service_location_token": "XATWYORS2H",
                    "journey_date": "-",
                    "journey": "",
                    "date_time": "2023-01-29 08:19:33",
                    "status": "Pending",
                    "adult_service_amount": "2875",
                    "total_adult": "2",
                    "children_service_amount": "2875",
                    "total_children": "2",
                    "net_amount": "11500",
                    "notes": "",
                    "rating": "0",
                    "review": "",
                    "review_date_time": "30 Nov, -0001",
                    "comment": "",
                    "comment_date_time": "-",
                    "description": "",
                    "report_reason_token": "",
                    "report_reason": "",
                    "report_description": "",
                    "reported_date_time": "30 Nov,-0001 12:00 AM",
                    "cancellation_policy_detail": [
                        {
                            "hours": "36",
                            "percentage": "50"
                        },
                        {
                            "hours": "24",
                            "percentage": "75"
                        },
                        {
                            "hours": "12",
                            "percentage": "100"
                        }
                    ],
                    "reschedule_policy": "contact@airportzo.com",
                    "can_be_cancelled": true,
                    "cancelled_by": "",
                    "cancellation_detail": {
                        "cancellation_hours": "24",
                        "cancellation_fee": "8625.00",
                        "cancellation_fee_perc": "75",
                        "airportzo_fee": "150",
                        "max_airportzo_fee": "150",
                        "cancelled_date": "-",
                        "refund_amount": "2725",
                        "refund_status": "Pending",
                        "refunded_date": "-",
                        "service_cost": "11500"
                    },
                    "az_sp_commision_amount": "0",
                    "sp_balance_credit": "-4090730",
                    "currency": "INR",
                    "markup_amount": "0",
                    "discount_amount": "0",
                    "is_coupon_service": "0",
                    "cart_coupon_type": "Excl Gst",
                    "discount": "6272",
                    "totalAdult_pdf": 1,
                    "total_additionalAdult_pdf": 1,
                    "totalChildren_pdf": 1,
                    "total_additionalChildren_pdf": 1,
                    "adult_serv_amt": 2436,
                    "child_serv_amt": 2436,
                    "add_adult_service_amount": 2436,
                    "add_children_service_amount": 2436,
                    "adult_discount": 146,
                    "child_discount": 146,
                    "add_adult_discount": 146,
                    "add_child_discount": 146,
                    "adult_net_amt": 2290,
                    "child_net_amt": 2290,
                    "add_adult_net_amt": 2290,
                    "add_child_net_amt": 2290,
                    "tax_rate1": "9% CGST",
                    "tax_rate2": "9% SGST",
                    "adult_tax_amt1": "206",
                    "adult_tax_amt2": "206",
                    "child_tax_amt1": "206",
                    "child_tax_amt2": "206",
                    "add_adult_tax_amt1": "206",
                    "add_adult_tax_amt2": "206",
                    "add_child_tax_amt1": "206",
                    "add_child_tax_amt2": "206",
                    "adult_sub_total": 2702,
                    "child_sub_total": 2702,
                    "add_adult_sub_total": 2702,
                    "add_child_sub_total": 2702,
                    "tax_type": 2,
                    "gst_no": "33AACCF8045D1ZM",
                    "place_serv": "Tamil Nadu",
                    "ut_code": "25",
                    "num_count": 8,
                    "max": "11500",
                    "ext_gst_serv_amt": 104528
                }
            ],
            "airport_type": "Transit",
            "flight_number": "sd,wd"
        },
        {
            "airport_token": "9244043212",
            "gmt_view": "+01:00",
            "airport_name": "Amsterdam Airport Schiphol",
            "airport_code": "AMS",
            "terminal_token": "1212121212",
            "terminal_name": "Terminal 3",
            "station_number": 4,
            "order_detail_array": [
                {
                    "id": "3407",
                    "token": "3201717541",
                    "booking_token": "2907910175",
                    "airport_token": "9244043212",
                    "airport_name": "Amsterdam Airport Schiphol",
                    "airport_code": "AMS",
                    "terminal_token": "1212121212",
                    "terminal_name": "Terminal 3",
                    "company_token": "3585484069",
                    "company_name": "Marhaba",
                    "company_email": "vetrikumar@airportzo.com",
                    "company_logo": "https://d1kbhg7ykrtfl2.cloudfront.net/service_provider_company/company_logo/Marhaba.jpg",
                    "company_image": "https://d1kbhg7ykrtfl2.cloudfront.net/service_provider_company/company_logo/marhaba_image.png",
                    "station_number": 4,
                    "flight_number": "",
                    "airport_type": "1573827082",
                    "airport_category": "1122334455",
                    "service_date_time": "30 Jan, 2023 17:00",
                    "service_date": "30 Jan, 2023",
                    "service_time": "05:00 PM",
                    "service_date_time_raw": "2023-01-30 17:00:00",
                    "service_token": "8471724742",
                    "service_name": "International-Arrival-Silver (Without Lounge)",
                    "service_type": "Bundle",
                    "service_location_token": "8892266800",
                    "journey_date": "-",
                    "journey": "",
                    "date_time": "2023-01-29 08:19:33",
                    "status": "Pending",
                    "adult_service_amount": "22370",
                    "total_adult": "2",
                    "children_service_amount": "22370",
                    "total_children": "2",
                    "net_amount": "45340",
                    "notes": "",
                    "rating": "0",
                    "review": "",
                    "review_date_time": "30 Nov, -0001",
                    "comment": "",
                    "comment_date_time": "-",
                    "description": "",
                    "report_reason_token": "",
                    "report_reason": "",
                    "report_description": "",
                    "reported_date_time": "30 Nov,-0001 12:00 AM",
                    "cancellation_policy_detail": [
                        {
                            "hours": "11",
                            "percentage": "11"
                        }
                    ],
                    "reschedule_policy": "sdfsdfds",
                    "can_be_cancelled": true,
                    "cancelled_by": "",
                    "cancellation_detail": {
                        "cancellation_hours": "11",
                        "cancellation_fee": "4987.40",
                        "cancellation_fee_perc": "11",
                        "airportzo_fee": "150",
                        "max_airportzo_fee": "150",
                        "cancelled_date": "-",
                        "refund_amount": "40202",
                        "refund_status": "Pending",
                        "refunded_date": "-",
                        "service_cost": "45340"
                    },
                    "az_sp_commision_amount": "0",
                    "sp_balance_credit": "-4136070",
                    "currency": "INR",
                    "markup_amount": "0",
                    "discount_amount": "0",
                    "is_coupon_service": "0",
                    "cart_coupon_type": "Excl Gst",
                    "discount": "6272",
                    "totalAdult_pdf": 1,
                    "total_additionalAdult_pdf": 1,
                    "totalChildren_pdf": 1,
                    "total_additionalChildren_pdf": 1,
                    "adult_serv_amt": 18958,
                    "child_serv_amt": 18958,
                    "add_adult_service_amount": 254,
                    "add_children_service_amount": 254,
                    "adult_discount": 1138,
                    "child_discount": 1138,
                    "add_adult_discount": 15,
                    "add_child_discount": 15,
                    "adult_net_amt": 17820,
                    "child_net_amt": 17820,
                    "add_adult_net_amt": 239,
                    "add_child_net_amt": 239,
                    "tax_rate1": "9% CGST",
                    "tax_rate2": "9% SGST",
                    "adult_tax_amt1": "1604",
                    "adult_tax_amt2": "1604",
                    "child_tax_amt1": "1604",
                    "child_tax_amt2": "1604",
                    "add_adult_tax_amt1": "22",
                    "add_adult_tax_amt2": "22",
                    "add_child_tax_amt1": "22",
                    "add_child_tax_amt2": "22",
                    "adult_sub_total": 21028,
                    "child_sub_total": 21028,
                    "add_adult_sub_total": 283,
                    "add_child_sub_total": 283,
                    "tax_type": 2,
                    "gst_no": "33AACCF8045D1ZM",
                    "place_serv": "Tamil Nadu",
                    "ut_code": "25",
                    "num_count": 8,
                    "max": "11500",
                    "ext_gst_serv_amt": 104528
                }
            ],
            "airport_type": "Arrival",
            "flight_number": "wd"
        }
    ],
    "passenger_detail": [
        {
            "passenger_type": "Contact",
            "passenger_array": [
                {
                    "id": "3014",
                    "token": "1417189282",
                    "booking_token": "2907910175",
                    "passenger_type": "Contact",
                    "user_passenger_token": "3561410696",
                    "title": "Mr",
                    "name": "Praveenraj",
                    "name_view": "Mr. Praveenraj",
                    "country_code": "+91",
                    "mobile_number": "8667533026",
                    "mobile_view": "+918667533026",
                    "email_id": "praveenraj@macappstudio.com",
                    "date_of_birth": "1970-01-01",
                    "age": "-"
                }
            ]
        },
        {
            "passenger_type": "Others",
            "passenger_array": [
                {
                    "id": "3015",
                    "token": "5936639131",
                    "booking_token": "2907910175",
                    "passenger_type": "Others",
                    "user_passenger_token": "5664941433",
                    "title": "Mr",
                    "name": "Ananad",
                    "name_view": "Mr. Ananad",
                    "country_code": "+91",
                    "mobile_number": "8667533026",
                    "mobile_view": "+918667533026",
                    "email_id": "pemkumar@gmail.com",
                    "date_of_birth": "1970-01-01",
                    "age": "-"
                },
                {
                    "id": "3016",
                    "token": "8044543662",
                    "booking_token": "2907910175",
                    "passenger_type": "Others",
                    "user_passenger_token": "2363238055",
                    "title": "Mr",
                    "name": "Premkumar",
                    "name_view": "Mr. Premkumar",
                    "country_code": "+91",
                    "mobile_number": "8667533026",
                    "mobile_view": "+918667533026",
                    "email_id": "akjbfa@gmail.com",
                    "date_of_birth": "1970-01-01",
                    "age": "-"
                },
                {
                    "id": "3017",
                    "token": "5025716810",
                    "booking_token": "2907910175",
                    "passenger_type": "Others",
                    "user_passenger_token": "2340585836",
                    "title": "Mr",
                    "name": "kumar",
                    "name_view": "Mr. kumar",
                    "country_code": "+91",
                    "mobile_number": "8667533026",
                    "mobile_view": "+918667533026",
                    "email_id": "kumar@gmail.com",
                    "date_of_birth": "1970-01-01",
                    "age": "-"
                }
            ]
        }
    ],
    "journey_detail": [
        {
            "id": "2002",
            "token": "9239160784",
            "booking_token": "2907910175",
            "depart_ttr_token": "NPOF7QRC6L",
            "depart_airport_code": "MAA",
            "depart_airport": "Chennai International Airport",
            "depart_terminal": "Terminal 1",
            "arrival_airport_code": "BLR",
            "arrival_airport": "Kempegowda International Airport",
            "arrival_terminal": "Terminal 1",
            "arrival_ttr_token": "H7IMUTB8AD",
            "depart_date": "30 Jan, 2023",
            "flight_number": "ewds"
        },
        {
            "id": "2003",
            "token": "7031803237",
            "booking_token": "2907910175",
            "depart_ttr_token": "H7IMUTB8AD",
            "depart_airport_code": "BLR",
            "depart_airport": "Kempegowda International Airport",
            "depart_terminal": "Terminal 1",
            "arrival_airport_code": "DXB",
            "arrival_airport": "Dubai International Airport",
            "arrival_terminal": "Terminal 1",
            "arrival_ttr_token": "9QWBCE27YT",
            "depart_date": "30 Jan, 2023",
            "flight_number": "sd"
        },
        {
            "id": "2004",
            "token": "4882685927",
            "booking_token": "2907910175",
            "depart_ttr_token": "9QWBCE27YT",
            "depart_airport_code": "DXB",
            "depart_airport": "Dubai International Airport",
            "depart_terminal": "Terminal 1",
            "arrival_airport_code": "AMS",
            "arrival_airport": "Amsterdam Airport Schiphol",
            "arrival_terminal": "Terminal 3",
            "arrival_ttr_token": "9768039908",
            "depart_date": "30 Jan, 2023",
            "flight_number": "wd"
        }
    ]
}';

$fetch_order_detail = json_decode($data);
// $booking_detail = $fetch_order_detail->data;
$invoice_template=invoice_template($fetch_order_detail);
store_invoice($invoice_template,$order_number,$source_path,$add_page);
// invoice_template($booking_detail);
?>